{"name": "countdown happens with the time set", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\CoundownTestSteps.py\", line 10, in open_browser\n    context.driver = webdriver.Chrome(executable_path=\"\\\\Drivers\\\\chromedriver.exe\")\n  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "steps": [{"name": "Given the url e.ggtimer.com is open", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\CoundownTestSteps.py\", line 10, in open_browser\n    context.driver = webdriver.Chrome(executable_path=\"\\\\Drivers\\\\chromedriver.exe\")\n  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\users\\rajya\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1613557173656, "stop": 1613557173770}, {"name": "When I set the timer to 25 and click on start button", "status": "skipped", "start": 1613557173774, "stop": 1613557173774}, {"name": "Then Count down starts by decrementing by 1 second", "status": "skipped", "start": 1613557173774, "stop": 1613557173774}, {"name": "And After the countdown ends a alert is displayed", "status": "skipped", "start": 1613557173774, "stop": 1613557173774}], "start": 1613557173655, "stop": 1613557173774, "uuid": "af00e943-16dd-4bc9-964e-42ad052f7dc1", "historyId": "d2110b0cda42fa65c8752ac94cbc6f78", "fullName": "to countdown the egg timer: countdown happens with the time set", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "to countdown the egg timer"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}